import type { Metadata } from 'next';
import { Jua, Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';

const jua = Jua({
  weight: '400',
  variable: '--font-jua',
  subsets: ['latin'],
});

const inter = Inter({
  weight: '400',
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${jua.variable} ${inter.variable}`}>
        <Header />
        {children}
        {/* <AuthProvider>
        </AuthProvider> */}
      </body>
    </html>
  );
}
